name: Deploy

run-name: '🔥 Deploy'

on: workflow_dispatch

permissions:
  actions: 'read'
  security-events: 'write'
  contents: 'write'
  checks: 'write'
  issues: 'write'
  pull-requests: 'write'

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  deploy:
    name: Deploy
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
