name: Deployer DISP

run-name: '🦑 Deployer dispatch'

on: 
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main

env:
  BRANCH_NAME: 'deployer-repo-checklist'
  OWNER: ${{ github.repository_owner }}

permissions:
  actions: 'read'
  security-events: 'write'
  contents: 'write'
  checks: 'write'
  issues: 'write'
  pull-requests: 'write'

jobs:
  dispatcher:
    name: Dispatcher
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-24.04
    outputs:
      repos: ${{ steps.dispatch.outputs.repos }}
      batch_id: ${{ steps.dispatch.outputs.batch_id }}
      pr_number: ${{ steps.dispatch.outputs.pr_number }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Configure git
        run: |
          git config --global user.name "${{ secrets.GIT_USER }}"
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
      - name: Dispatch workflow to repos in PR list
        id: dispatch
        run: |
          for file in deployments/latest_deployed_repos-*.txt; do
            [ -e "$file" ] || { echo "No deployed repos file found"; exit 1; }
            BATCH_ID="${file##*-}"
            BATCH_ID="${BATCH_ID%.txt}"
            while read -r repo; do
              echo "Dispatching workflow to $repo"
              # gh workflow run deploy.yml --repo extrapreneur/$repo
            done < "$file"
            REPOS=$(paste -sd, "$file")
            echo "repos=$REPOS" >> $GITHUB_OUTPUT
            echo "batch_id=$BATCH_ID" >> $GITHUB_OUTPUT
          done
        env:
          GH_TOKEN: ${{ secrets.GIT_USER_PAT }}
      - name: Label merged PR
        run: |
          DATE_NOW=$(date +%Y-%m-%d)
          LABEL_NAME="deployed-$DATE_NOW"
          COLOR="#5f9b86"
          if ! gh label list --repo "${{ github.repository }}" | grep -q "^$LABEL_NAME\b"; then
            gh label create "$LABEL_NAME" --color "$COLOR" --description "Deployment complete" --repo "${{ github.repository }}"
          fi
          PR_NUMBER=$(gh pr list --state merged --head "${{ env.BRANCH_NAME }}" --json number -q '.[0].number')
          gh pr edit "$PR_NUMBER" --add-label "$LABEL_NAME" --repo "${{ github.repository }}"
        env:
          GH_TOKEN: ${{ secrets.GIT_USER_PAT }}
      - name: Label merged PR with batch ID
        id: label-batch-id
        run: |
          BATCH_LABEL="id-${{ steps.dispatch.outputs.batch_id }}"
          COLOR="#f38126"
          # Create the label if it doesn't exist
          if ! gh label list --repo "${{ github.repository }}" | grep -q "^$BATCH_LABEL\b"; then
            gh label create "$BATCH_LABEL" --color "$COLOR" --description "Batch deployment ID" --repo "${{ github.repository }}"
          fi
          PR_NUMBER=$(gh pr list --state merged --head "${{ env.BRANCH_NAME }}" --json number -q '.[0].number')
          gh pr edit "$PR_NUMBER" --add-label "$BATCH_LABEL" --repo "${{ github.repository }}"
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GIT_USER_PAT }}
  summary:
    name: Summary
    runs-on: ubuntu-24.04
    needs: dispatcher
    steps:
      - name: Create summary
        run: |
          PR_URL="https://github.com/${{ env.OWNER }}/${{ github.event.repository.name }}/pulls/${{ needs.dispatcher.outputs.pr_number }}"
          echo "## 🦑 Deployed" > summary.md
          echo "Repositories from the latest PR merge" >> summary.md
          echo "### Batch ID: [${{ needs.dispatcher.outputs.batch_id }}]($PR_URL)" >> summary.md
          echo "### Repositories:" >> summary.md
          echo "" >> summary.md
          echo "| Repository |" >> summary.md
          echo "|------------|" >> summary.md
          for repo in $(echo "${{ needs.dispatcher.outputs.repos }}" | tr ',' '\n'); do
            echo "| $repo |" >> summary.md
          done
          echo "" >> summary.md
        env:
          GH_TOKEN: ${{ secrets.GIT_USER_PAT }}
      - name: Render summary
        run: |
          SUMMARY=$(cat summary.md)
          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY